In [7]:
import numpy as np

my_arr = np.arange(1_000_000)

In [8]:
my_list = list(range(1_000_000))

In [9]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [10]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [11]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [12]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [13]:
data.shape

(2, 3)

In [14]:
data.dtype

dtype('float64')

In [15]:
# create an array with the keyword
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [16]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [17]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [18]:
arr2 = np.array(data2)

In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)

In [22]:
arr2.dtype

dtype('int64')